include:
  # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Jobs/Secret-Detection.latest.gitlab-ci.yml
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml
  # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Jobs/Dependency-Scanning.latest.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - build
  - unit_tests
  - test
  - sonar

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone
  DISABLE_QUALITY_GATES: 'false'
  FORCE_REBUILDING_DEPENDENCIES: 'false'
  # Gitlab Secret Detection
  ENABLE_SECRET_DETECTION: "true"
  # Gitlab dependency scanning
  DEPENDENCY_SCANNING_DISABLED: 'false'
  DS_ENFORCE_NEW_ANALYZER: 'true'
  DISABLE_FAIL_ON_VULNERABILITY_CHECK: 'false'

default:
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dracoon.com/dracoon/cicd/pipeline/sdk-swift-sonar.git
    - SONAR_BRANCH=$CI_COMMIT_REF_NAME
    - ./sdk-swift-sonar/setup.sh "${SONAR_BRANCH}" "${CI_COMMIT_SHORT_SHA}"
  id_tokens:
    ID_TOKEN:
      aud: https://vault.dracoon.net

build:
  before_script:
    - if [ $FORCE_REBUILDING_DEPENDENCIES == "true" ]; then rm -rf /opt/gitlab/Library/CarthageCache/*; else echo "Using local Carthage cache"; fi
    - !reference ["default", "before_script"]
  dependencies: []
  stage: build
  script:
    - bundle exec fastlane build
    - sh /opt/gitlab/Library/cleanupArtifacts.sh
    - mkdir /opt/gitlab/Library/Artifacts/${CI_PIPELINE_ID}
  tags:
    - darwin/arm64
    - ios-build

unit_tests:
  dependencies: []
  stage: unit_tests
  script:
    - bundle exec fastlane runUnitTests
    - cp sdk-swift-sonar/printCodeCoverage.sh TestResults/Logs/Test/
    - sh TestResults/Logs/Test/printCodeCoverage.sh
    - cp -r TestResults /opt/gitlab/Library/Artifacts/${CI_PIPELINE_ID}
  coverage: '/Code coverage: \d+\.\d+/'
  tags:
    - darwin/arm64
    - ios-build
    
dependency-scanning:
  stage: test
  variables:
    ANALYZER_SUPPORTED_FILES: "Package.resolved"
  needs:
    - job: build
      artifacts: true
  before_script:
    - echo "start dependency scanning"
  rules:
    - if: $DEPENDENCY_SCANNING_DISABLED != 'true' && $DEPENDENCY_SCANNING_DISABLED != '1'
      when: on_success
    - when: never
  allow_failure: false
  artifacts:
    expire_in: 1 day
    
sbom-vulnerability-evaluation:
  stage: test
  rules:
    - if: $DISABLE_FAIL_ON_VULNERABILITY_CHECK == 'true'
      allow_failure: true
      when: on_success
    - if: $DISABLE_FAIL_ON_VULNERABILITY_CHECK == 'false'
      allow_failure: false
      when: on_success
  needs:
    - job: dependency-scanning
  before_script:
    - apt-get -qq update
    - apt-get install -y jq
    - apt-get install -y git
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dracoon.com/dracoon/cicd/pipeline/sdk-swift-sonar.git
  script:
    - |
      chmod +x ./sdk-swift-sonar/evaluate-sbom.sh
      ./sdk-swift-sonar/evaluate-sbom.sh gl-sbom-swift-swift.cdx.json

graphql-vulnerability-evaluation:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: never
    - if: $DISABLE_FAIL_ON_VULNERABILITY_CHECK == 'true'
      allow_failure: true
      when: on_success
    - if: $DISABLE_FAIL_ON_VULNERABILITY_CHECK == 'false'
      allow_failure: false
      when: on_success
  needs:
    - job: dependency-scanning
  before_script:
    - apt-get -qq update
    - apt-get install -y jq
    - apt-get install -y curl
    - apt-get install -y git
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dracoon.com/dracoon/cicd/pipeline/sdk-swift-sonar.git
  script:
    - |
      chmod +x ./sdk-swift-sonar/evaluate-graphql.sh
      ./sdk-swift-sonar/evaluate-graphql.sh $GRAPHQL_ACCESS_TOKEN $CI_PROJECT_PATH

secret_detection:
  stage: test
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dracoon.com/dracoon/cicd/pipeline/sdk-swift-sonar.git
  needs:
    - job: build
  rules:
    - if: $ENABLE_SECRET_DETECTION != "true" ||
        $SECRET_DETECTION_DISABLED == "true"
      when: never
    - when: on_success
  allow_failure: false

sonar:
  stage: sonar
  secrets:
    SONAR_TOKEN:
      vault: Sonar/token@Build-Environment
      file: false
  script:
    - cp -r /opt/gitlab/Library/Artifacts/${CI_PIPELINE_ID}/TestResults .
    - if [ $CI_PIPELINE_SOURCE == "merge_request_event" ]; then SONAR_BRANCH=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME; else SONAR_BRANCH=$CI_COMMIT_REF_NAME; fi
    - bundle exec fastlane runSonar token:$SONAR_TOKEN gitBranch:$SONAR_BRANCH commitHash:$CI_COMMIT_SHORT_SHA
  rules:
    - if: $DISABLE_QUALITY_GATES == "false"
      when: on_success
    - if: $DISABLE_QUALITY_GATES == "true"
      allow_failure: true
      when: on_success
  tags:
    - darwin/arm64
    - ios-build
