stages:
  - unit_tests
  - sonar

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dracoon.com/dracoon/ios/client/sdk-swift-sonar.git
  - sh sdk-swift-sonar/setup.sh

unit_tests:
  dependencies: []
  stage: unit_tests
  script:
    - bundle exec fastlane runUnitTests
    - cp sdk-swift-sonar/printCodeCoverage.sh TestResults/Logs/Test/
    - sh TestResults/Logs/Test/printCodeCoverage.sh
  coverage: '/Code coverage: \d+\.\d+/'
  tags:
    - darwin-amd64

sonar:
  stage: sonar
  script:
    - bundle exec fastlane runSonar
  tags:
    - darwin-amd64
