//
// ActiveDirectory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActiveDirectory: Codable {

    /** ID */
    public var _id: Int
    /** Unique name for an Active Directory configuration */
    public var alias: String
    /** Is available for all customers */
    public var isGlobalAvailable: Bool


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case alias
        case isGlobalAvailable
    }


}

