//
// ActiveDirectoryAuthInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActiveDirectoryAuthInfo: Codable {

    /** List of available Active Directories */
    public var items: [ActiveDirectory]



}

