//
// AuditNodeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuditNodeResponse: Codable {

    /** Node ID */
    public var nodeId: Int64
    /** Node name */
    public var nodeName: String
    /** Parent node path &#x60;/&#x60; if node is a root node (room) */
    public var nodeParentPath: String
    /** Number of direct children (no recursion; for rooms / folders only) */
    public var nodeCntChildren: Int
    /** List of assigned users with permissions */
    public var auditUserPermissionList: [AuditUserPermission]
    /** Parent node ID (room or folder) */
    public var nodeParentId: Int64?
    /** Node size in byte */
    public var nodeSize: Int64?
    /** Is Recycle Bin active (for rooms only) (default: false) */
    public var nodeHasRecycleBin: Bool?
    /** Retention period for deleted nodes in days (Integer between 0 and 9999) */
    public var nodeRecycleBinRetentionPeriod: Int?
    /** Quota in byte */
    public var nodeQuota: Int64?
    /** Encryption state */
    public var nodeIsEncrypted: Bool?
    /** Is activities log active (for rooms only) (default: true) */
    public var nodeHasActivitiesLog: Bool?
    /** Creation date */
    public var nodeCreatedAt: Date?
    /** Created by user info */
    public var nodeCreatedBy: UserInfo?
    /** Modification date */
    public var nodeUpdatedAt: Date?
    /** Modified by user info */
    public var nodeUpdatedBy: UserInfo?



}

