//
// AuthConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthConfig: Codable {

    /** List of authentication methods */
    public var authMethods: [AuthMethod]



}

