//
// AuthInitResources.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthInitResources: Codable {

    /** Authentication methods: * &#x60;sql&#x60; * &#x60;active_directory&#x60; * &#x60;radius&#x60; * &#x60;openid&#x60; */
    public var authTypes: [KeyValueEntry]
    /** &#x60;DEPRECATED&#x60;: Supported languages */
    public var languages: [Language]



}

