//
// BrandingConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrandingConfig: Codable {

    /** Access URL to to the Branding Portal */
    public var brandingProviderUrl: String?
    /** Branding UUID */
    public var brandingQualifier: String?



}

