//
// ChunkUploadResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChunkUploadResponse: Codable {

    /** Chunk size */
    public var size: Int64
    /** Hash value of transferred chunk */
    public var hash: String



}

