//
// ConfigOptionList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ConfigOptionList: Codable {

    /** List of key-value pairs */
    public var items: [KeyValueEntry]



}

