//
// CreateShareUploadChannelRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateShareUploadChannelRequest: Codable {

    /** File name */
    public var name: String
    /** File size in byte */
    public var size: Int64?
    /** Password */
    public var password: String?



}

