//
// CreateFolderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateFolderRequest: Codable {

    /** Parent node ID (room or folder) */
    public var parentId: Int64
    /** Name */
    public var name: String
    /** User notes Use empty string to remove. */
    public var notes: String?



}

