//
// DeletedNodeSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeletedNodeSummary: Codable {

    public enum ModelType: String, Codable { 
        case room = "room"
        case folder = "folder"
    }
    /** Parent node ID (room or folder) */
    public var parentId: Int64
    /** Parent node path &#x60;/&#x60; if node is a root node (room) */
    public var parentPath: String
    /** Node name */
    public var name: String
    /** Node type */
    public var type: ModelType
    /** Number of deleted versions of this file */
    public var cntVersions: Int
    /** First deleted version */
    public var firstDeletedAt: Date
    /** Last deleted version */
    public var lastDeletedAt: Date
    /** Node ID of last deleted version */
    public var lastDeletedNodeId: Int64



}

