//
// DeleteDeletedNodesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeleteDeletedNodesRequest: Codable {

    /** List of deleted node IDs */
    public var deletedNodeIds: [Int64]



}

