//
// EncryptionInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EncryptionInfo: Codable {

    public enum UserKeyState: String, Codable { 
        case _none = "none"
        case pending = "pending"
        case available = "available"
    }
    public enum RoomKeyState: String, Codable { 
        case _none = "none"
        case pending = "pending"
        case available = "available"
    }
    public enum DataSpaceKeyState: String, Codable { 
        case _none = "none"
        case pending = "pending"
        case available = "available"
    }
    /** User key state */
    public var userKeyState: UserKeyState
    /** Room key state */
    public var roomKeyState: RoomKeyState
    /** DRACOON key state */
    public var dataSpaceKeyState: DataSpaceKeyState



}

