//
// FileFileKeys.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import crypto_sdk


public struct FileFileKeys: Codable {

    /** File ID */
    public var _id: Int64?
    /** File key container (key, iv, version and tag) */
    public var fileKeyContainer: EncryptedFileKey


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case fileKeyContainer
    }


}

