//
// FirstAdminUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FirstAdminUser: Codable {

    public enum Gender: String, Codable { 
        case m = "m"
        case f = "f"
        case n = "n"
    }
    /** User login name */
    public var login: String
    /** User first name */
    public var firstName: String
    /** User last name */
    public var lastName: String
    /** If true, the user must change the &#x60;userName&#x60; at the first login. (default: false) */
    public var needsToChangeUserName: Bool?
    /** An initial password may be preset */
    public var password: String?
    /** Job title */
    public var title: String?
    /** Gender */
    public var gender: Gender?
    /** Language ID or ISO 639-1 code */
    public var language: String?
    /** Notify user about his new account (default: true) */
    public var notifyUser: Bool?
    /** Authentication methods: * &#x60;sql&#x60; * &#x60;active_directory&#x60; * &#x60;radius&#x60; * &#x60;openid&#x60; */
    public var authMethods: [UserAuthMethod]?
    /** Email (not used) */
    public var email: String?



}

