//
// KeyValueEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct KeyValueEntry: Codable {

    /** Entry key */
    public var key: String
    /** Entry value */
    public var value: String



}

