//
// Language.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Language: Codable {

    /** Language ID */
    public var languageId: Int
    /** Description */
    public var _description: String
    /** ISO 639-1 code */
    public var isoCode: String


    public enum CodingKeys: String, CodingKey { 
        case languageId
        case _description = "description"
        case isoCode
    }


}

