//
// LogOperationList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LogOperationList: Codable {

    /** List of all log operations */
    public var operationList: [LogOperation]



}

