//
// ModelRange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelRange: Codable {

    /** Range offset */
    public var offset: Int64
    /** Range limit */
    public var limit: Int64
    /** Total items available */
    public var total: Int64



}

