//
// NodeList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodeList: Codable {

    /** Range */
    public var range: ModelRange
    /** List of nodes */
    public var items: [Node]



}

