//
// NotRestoredNode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NotRestoredNode: Codable {

    public enum ModelType: String, Codable { 
        case room = "room"
        case folder = "folder"
    }
    /** Parent node ID (room or folder) */
    public var parentId: Int64
    /** Parent node path &#x60;/&#x60; if node is a root node (room) */
    public var parentPath: String
    /** Node name */
    public var name: String
    /** Node type */
    public var type: ModelType
    /** Not restored node ID */
    public var _id: Int64?


    public enum CodingKeys: String, CodingKey { 
        case parentId
        case parentPath
        case name
        case type
        case _id = "id"
    }


}

