//
// OpenIdAuthInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OpenIdAuthInfo: Codable {

    /** List of available OpenID Connect identity providers */
    public var items: [OpenIdProvider]



}

