//
// PendingAssignmentList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PendingAssignmentList: Codable {

    /** List of pending assignment information */
    public var items: [PendingAssignmentData]
    /** Range */
    public var range: ModelRange?



}

