//
// PendingUserData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PendingUserData: Codable {

    /** Unique identifier for the user */
    public var _id: Int64
    /** User login name */
    public var login: String
    /** Display name */
    public var displayName: String
    /** Email (not used) */
    public var email: String


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case login
        case displayName
        case email
    }


}

