//
// PendingGroupData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PendingGroupData: Codable {

    /** Unique identifier for the group */
    public var _id: Int64
    /** Group name */
    public var name: String


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
    }


}

