//
// PublicUploadShare.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicUploadShare: Codable {

    /** Is share protected by password */
    public var isProtected: Bool
    /** Creation date */
    public var createdAt: Date
    /** &#x60;DEPRECATED&#x60;: Maximal amount of files to upload */
    public var maxSlots: Int
    /** Share display name (alias name) */
    public var name: String?
    /** Encryption state */
    public var isEncrypted: Bool?
    /** Expiration date */
    public var expireAt: Date?
    /** User notes Use empty string to remove. */
    public var notes: String?
    /** List of (public) uploaded files */
    public var uploadedFiles: [PublicUploadedFileData]?
    /** List of user public keys */
    public var userUserPublicKeyList: UserUserPublicKeyList?
    /** Allow display of already uploaded files (default: false) */
    public var showUploadedFiles: Bool?
    /** &#x60;DEPRECATED&#x60;: Maximal total size of uploaded files (in bytes) */
    public var maxSize: Double?



}

