//
// PublicUploadedFileData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicUploadedFileData: Codable {

    /** Name */
    public var name: String
    /** File size in byte */
    public var size: Int64
    /** Creation date */
    public var createdAt: Date
    /** Hash value of transferred file */
    public var hash: String?



}

