//
// PublicDownloadShare.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicDownloadShare: Codable {

    /** Is share protected by password */
    public var isProtected: Bool
    /** File name */
    public var fileName: String
    /** File size or container size not compressed (in bytes) */
    public var size: Int64
    /** Downloads limit reached */
    public var limitReached: Bool
    /** Creator name */
    public var creatorName: String
    /** Creation date */
    public var createdAt: Date
    /** Share display name (alias name) */
    public var name: String?
    /** Creator user name */
    public var creatorUsername: String?
    /** Expiration date */
    public var expireAt: Date?
    /** User notes Use empty string to remove. */
    public var notes: String?
    /** Encryption state */
    public var isEncrypted: Bool?
    /** Encrypted file key for shares out of encrypted rooms */
    public var fileKey: FileKey?
    /** Private key container (private key and version) */
    public var privateKeyContainer: PrivateKeyContainer?



}

