//
// RadiusChallengeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RadiusChallengeResponse: Codable {

    /** HTTP status code */
    public var code: Int?
    /** For RADIUS Access-Challenge If a &#x60;replyState&#x60; is returned, it must be included as &#x60;state&#x60; in the following request. */
    public var replyState: String?
    /** HTTP status code description */
    public var message: String?
    /** RADIUS Reply-Message Instruction how to handle the situation. */
    public var replyMessage: String?
    /** Debug information */
    public var debugInfo: String?
    /** Error code */
    public var errorCode: Int?



}

