//
// ResetPasswordWithTokenRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResetPasswordWithTokenRequest: Codable {

    /** New password */
    public var password: String



}

