//
// ResetPasswordRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResetPasswordRequest: Codable {

    /** User login name */
    public var login: String
    /** Language ID or ISO 639-1 code */
    public var language: String?



}

