//
// RoleList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoleList: Codable {

    /** List of roles */
    public var items: [Role]



}

