//
// RoomUsersAddBatchRequestItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomUsersAddBatchRequestItem: Codable {

    /** Unique identifier for the user */
    public var _id: Int64
    /** Available permissions for this node */
    public var permissions: NodePermissions


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case permissions
    }


}

