//
// RoomUsersDeleteBatchRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomUsersDeleteBatchRequest: Codable {

    /** List of user IDs */
    public var ids: [Int64]



}

