//
// RoomUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomUser: Codable {

    /** Unique identifier for the user */
    public var _id: Int64
    /** Is user granted room permissions */
    public var isGranted: Bool
    /** User login name */
    public var login: String
    /** Display name */
    public var displayName: String
    /** Email (not used) */
    public var email: String
    /** Available permissions for this node */
    public var permissions: NodePermissions?
    /** Public key container (private key and version) */
    public var publicKeyContainer: PublicKeyContainer?


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case isGranted
        case login
        case displayName
        case email
        case permissions
        case publicKeyContainer
    }


}

