//
// RoomGroupsAddBatchRequestItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomGroupsAddBatchRequestItem: Codable {

    public enum NewGroupMemberAcceptance: String, Codable { 
        case autoallow = "autoallow"
        case pending = "pending"
    }
    /** Unique identifier for the group */
    public var _id: Int64
    /** Available permissions for this node */
    public var permissions: NodePermissions
    /** Behaviour when new users are added to the group: * &#x60;autoallow&#x60; * &#x60;pending&#x60;  Only relevant if &#x60;adminGroupIds&#x60; has items. (default: &#x60;autoallow&#x60;) */
    public var newGroupMemberAcceptance: NewGroupMemberAcceptance?


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case permissions
        case newGroupMemberAcceptance
    }


}

