//
// RoomGroupsDeleteBatchRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomGroupsDeleteBatchRequest: Codable {

    /** List of group IDs */
    public var ids: [Int64]



}

