//
// RoomUsersAddBatchRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomUsersAddBatchRequest: Codable {

    /** List of room-user mappings */
    public var items: [RoomUsersAddBatchRequestItem]



}

