//
// RoomGroupsAddBatchRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomGroupsAddBatchRequest: Codable {

    /** List of room-group mappings */
    public var items: [RoomGroupsAddBatchRequestItem]



}

