//
// S3ConfigCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct S3ConfigCreateRequest: Codable {

    /** S3 object storage endpoint URL */
    public var endpointUrl: String
    /** Access key */
    public var accessKey: String
    /** Secret to key */
    public var secretKey: String
    /** S3 bucket name */
    public var bucketName: String
    /** S3 region */
    public var region: String?



}

