//
// SdsServerTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SdsServerTime: Codable {

    /** DRACOON server time */
    public var time: Date?



}

