//
// SyslogEventList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SyslogEventList: Codable {

    /** Range */
    public var range: ModelRange
    /** List of log events */
    public var items: [SyslogEvent]



}

