//
// SyslogConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SyslogConfig: Codable {

    public enum ModelProtocol: String, Codable { 
        case tcp = "TCP"
        case udp = "UDP"
    }
    /** Is syslog enabled? */
    public var enabled: Bool?
    /** Syslog Server (IP or FQDN) */
    public var host: String?
    /** Syslog server port */
    public var port: Int?
    /** Protocol to connect to syslog server */
    public var _protocol: ModelProtocol?
    /** Determines whether user’s IP address is logged on login. */
    public var logIpEnabled: Bool?


    public enum CodingKeys: String, CodingKey { 
        case enabled
        case host
        case port
        case _protocol = "protocol"
        case logIpEnabled
    }


}

