//
// UpdateOAuthClientRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateOAuthClientRequest: Codable {

    /** Secret, which uses the client for authentication. */
    public var clientSecret: String?
    /** Authorized grant types cf. [RFC 6749](https://tools.ietf.org/html/rfc6749) */
    public var grantTypes: [String]?
    /** URIs, to which a user is redirected after authorization. */
    public var redirectUris: [String]?
    /** Validity of the access token in seconds. */
    public var accessTokenValidity: Int?
    /** Validity of the refresh token in seconds. */
    public var refreshTokenValidity: Int?
    /** &#x60;DEPRECATED&#x60;: URL, to which a user is redirected after authorization. */
    public var redirectUrl: String?



}

