//
// UpdateUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateUserRequest: Codable {

    public enum Gender: String, Codable { 
        case m = "m"
        case f = "f"
        case n = "n"
    }
    /** Job title */
    public var title: String?
    /** User first name */
    public var firstName: String?
    /** User last name */
    public var lastName: String?
    /** Gender */
    public var gender: Gender?
    /** User lock status: * &#x60;0&#x60; - locked * &#x60;1&#x60; - Web access allowed * &#x60;2&#x60; - Web and mobile access allowed */
    public var lockStatus: Int?
    /** Expiration date / time */
    public var expiration: ObjectExpiration?
    /** Authentication methods: * &#x60;sql&#x60; * &#x60;active_directory&#x60; * &#x60;radius&#x60; * &#x60;openid&#x60; */
    public var authMethods: [UserAuthMethod]?
    /** Email (not used) */
    public var email: String?



}

