//
// UpdateMailServerConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateMailServerConfig: Codable {

    /** Email server host */
    public var host: String?
    /** Email server port */
    public var port: Int?
    /** User name for email server */
    public var username: String?
    /** Password for email server */
    public var password: String?
    /** Set &#39;true&#39; if the email server requires authentication. */
    public var authenticationEnabled: Bool?
    /** Email server requires SSL connection? Requires &#39;starttlsEnabled&#39; to be &#39;false&#39; */
    public var sslEnabled: Bool?
    /** Email server requires StartTLS connection? Requires &#39;sslEnabled&#39; to be &#39;false&#39; */
    public var starttlsEnabled: Bool?
    /** Set &#39;true&#39; to reset email server &#39;username&#39;. */
    public var resetUsername: Bool?
    /** Set &#39;true&#39; to reset email server &#39;password&#39;. */
    public var resetPassword: Bool?



}

