//
// UpdateBrandingConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateBrandingConfig: Codable {

    /** Access URL to to the Branding Portal */
    public var brandingProviderUrl: String?
    /** Branding UUID */
    public var brandingQualifier: String?
    /** Set &#39;true&#39; to reset &#39;brandingProviderUrl&#39;. */
    public var resetBrandingProviderUrl: Bool?
    /** Set &#39;true&#39; to reset &#39;brandingQualifier&#39;. */
    public var resetBrandingQualifier: Bool?



}

