//
// UpdateCustomerRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateCustomerRequest: Codable {

    public enum CustomerContractType: String, Codable { 
        case free = "free"
        case demo = "demo"
        case pay = "pay"
    }
    /** Company name */
    public var companyName: String?
    /** Customer type */
    public var customerContractType: CustomerContractType?
    /** Provider customer ID value (relevant only for type &#x60;pay&#x60;) */
    public var providerCustomerId: String?
    /** Maximal disc space which can be allocated by customer in bytes. */
    public var quotaMax: Int64?
    /** Maximal number of users */
    public var userMax: Int?
    /** Customer lock status: * &#x60;false&#x60; - unlocked * &#x60;true&#x60; - locked  All users of this customer will be blocked and can not login anymore. (default: false) */
    public var lockStatus: Bool?



}

