//
// UserFileKeySetBatchRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserFileKeySetBatchRequest: Codable {

    /** List of user file keys */
    public var items: [UserFileKeySetRequest]



}

