//
// UserUserPublicKeyList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserUserPublicKeyList: Codable {

    /** List of user public keys */
    public var items: [UserUserPublicKey]



}

