//
// UserFileKey.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserFileKey: Codable {

    /** Unique identifier for the user */
    public var userId: Int64
    /** User file key */
    public var fileKey: FileKey



}

