//
// UserFileKeySetRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import crypto_sdk


public struct UserFileKeySetRequest: Codable {

    /** File ID */
    public var fileId: Int64
    /** Unique identifier for the user */
    public var userId: Int64
    /** User file key */
    public var fileKey: EncryptedFileKey



}

