//
// ZipDownloadRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ZipDownloadRequest: Codable {

    /** List of node IDs */
    public var nodeIds: [Int64]



}

