//
// ActiveDirectoryConfigList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActiveDirectoryConfigList: Codable {

    /** List of Active Directory configurations */
    public var items: [ActiveDirectoryConfig]



}

