//
// AuthMethod.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthMethod: Codable, Sendable {

    /** Authentication methods: * &#x60;basic&#x60; (or &#x60;sql&#x60;) * &#x60;active_directory&#x60; * &#x60;radius&#x60; * &#x60;openid&#x60; */
    public var name: String
    /** Is enabled */
    public var isEnabled: Bool
    /** Priority (smaller values have higher priority) */
    public var priority: Int



}

