//
// BrandingServerInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrandingServerInfo: Codable {

    /** UUID of Branding */
    public var brandingServerBrandingId: String
    /** &#x60;DEPRECATED&#x60;: Branding server customer UUID */
    public var brandingServerCustomer: String
    /** &#x60;DEPRECATED&#x60;: Branding server URL */
    public var brandingServerUrl: String?



}

