//
// ChangeUserPasswordRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChangeUserPasswordRequest: Codable {

    /** Old password */
    public var oldPassword: String
    /** New password */
    public var newPassword: String



}

