//
// ChangeGroupMembersRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChangeGroupMembersRequest: Codable {

    /** List of group IDs */
    public var ids: [Int64]



}

