//
// ConfigRoomRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ConfigRoomRequest: Codable {

    public enum NewGroupMemberAcceptance: String, Codable { 
        case autoallow = "autoallow"
        case pending = "pending"
    }
    /** Is Recycle Bin active (for rooms only) (default: false) */
    public var hasRecycleBin: Bool?
    /** Retention period for deleted nodes in days (Integer between 0 and 9999) */
    public var recycleBinRetentionPeriod: Int?
    /** Inherit permissions from parent room (default: &#x60;false&#x60; if &#x60;parentId&#x60; is &#x60;0&#x60;; otherwise: &#x60;true&#x60;) */
    public var inheritPermissions: Bool?
    /** Take over existing permissions */
    public var takeOverPermissions: Bool?
    /** List of user ids A room requires at least one admin (user or group) */
    public var adminIds: [Int64]?
    /** List of group ids A room requires at least one admin (user or group) */
    public var adminGroupIds: [Int64]?
    /** Behaviour when new users are added to the group: * &#x60;autoallow&#x60; * &#x60;pending&#x60;  Only relevant if &#x60;adminGroupIds&#x60; has items. (default: &#x60;autoallow&#x60;) */
    public var newGroupMemberAcceptance: NewGroupMemberAcceptance?
    /** Is activities log active (for rooms only) (default: true) */
    public var hasActivitiesLog: Bool?



}

