//
// ConflictNode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ConflictNode: Codable, Sendable {

    /** Node ID */
    public var nodeId: Int64?
    /** Name */
    public var name: String?
    /** Error code */
    public var errorCode: Int?
    /** Error message */
    public var errorMessage: String?



}

