//
// CreateFileUploadResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/// - Tag: CreateFileUploadResponse
public struct CreateFileUploadResponse: Codable {

    /** (public) Upload URL */
    public var uploadUrl: String
    /** Upload (channel) ID */
    public var uploadId: String

}

