//
// CreateFileUploadRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/// - Tag: CreateFileUploadRequest
public struct CreateFileUploadRequest: Codable, Sendable {

    public enum Classification: Int, Codable, Sendable {
        case PUBLIC = 1
        case INTERNAL_USE = 2
        case CONFIDENTAL = 3
        case STRICTLY_CONFIDENTAL = 4
    }
    /** Parent node ID (room or folder) */
    public var parentId: Int64
    /** File name */
    public var name: String
    /** Classification ID (for files only): * &#x60;1&#x60; - public * &#x60;2&#x60; - for internal use only * &#x60;3&#x60; - confidential * &#x60;4&#x60; - strictly confidential
     This field is mandatory for API version < 4.9. From version 4.9 default classification is set if this field is empty.
     */
    public var classification: Classification?
    /** File size in byte */
    public var size: Int64?
    /** Expiration date / time */
    public var expiration: ObjectExpiration?
    /** User notes Use empty string to remove. */
    public var notes: String?
    /** Indicates direct upload to S3
     [Since version 4.13.0] */
    public var directS3Upload: Bool?
    /** Time the node was created on external file system [Since version 4.22.0] */
    public var timestampCreation: String?
    /** Time the content of a node was last modified on external file system [Since version 4.22.0] */
    public var timestampModification: String?


}

