//
// CreateDownloadShareRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import crypto_sdk

/// - Tag: CreateDownloadShareRequest
public struct CreateDownloadShareRequest: Codable {

    /** Source node ID */
    public var nodeId: Int64
    /** Alias name */
    public var name: String?
    /** Access password */
    public var password: String?
    /** Expiration date / time */
    public var expiration: ObjectExpiration?
    /** User notes Use empty string to remove. */
    public var notes: String?
    /** Show creator first and last name. (default: false) */
    public var showCreatorName: Bool?
    /** Show creator email address. (default: false) */
    public var showCreatorUsername: Bool?
    /** Notify creator on every download. (default: false) */
    public var notifyCreator: Bool?
    /** Max allowed downloads */
    public var maxDownloads: Int?
    /** Notify recipients (default: false) */
    public var sendMail: Bool?
    /** CSV string of recipient emails */
    public var mailRecipients: String?
    /** Notification email subject */
    public var mailSubject: String?
    /** Notification email content */
    public var mailBody: String?
    /** Keypair for Download Share pseudo-user */
    public var keyPair: UserKeyPair?
    /** Encrypted file key for shares out of encrypted rooms */
    public var fileKey: EncryptedFileKey?
    /** Send share password via SMS (default: false) */
    public var sendSms: Bool?
    /** CSV string of recipient MSISDNs */
    public var smsRecipients: String?



}

