//
// CreateFileUploadResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateFileUploadResponse: Codable {

    /** (public) Upload URL */
    public var uploadUrl: String
    /** Upload (channel) ID */
    public var uploadId: String
    
    /** [Deprecated since v4.3.0] Upload token */
    public var token: String



}

