//
// CreateFileUploadResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateFileUploadResponse: Codable {

    /** Upload (channel) ID */
    public var uploadId: String
    /** &#x60;DEPRECATED&#x60;: Upload token */
    public var token: String
    /** (public) Upload URL */
    public var uploadUrl: String?



}

