//
// CreateUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateUserRequest: Codable {

    public enum Gender: String, Codable { 
        case m = "m"
        case f = "f"
        case n = "n"
    }
    /** User first name */
    public var firstName: String
    /** User last name */
    public var lastName: String
    /** Authentication methods: * &#x60;sql&#x60; * &#x60;active_directory&#x60; * &#x60;radius&#x60; * &#x60;openid&#x60; */
    public var authMethods: [UserAuthMethod]
    /** User login name */
    public var login: String
    /** Job title */
    public var title: String?
    /** Gender */
    public var gender: Gender?
    /** Expiration date / time */
    public var expiration: ObjectExpiration?
    /** Email (not used) */
    public var email: String?



}

