//
// CustomerList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomerList: Codable, Sendable {

    /** Range */
    public var range: ModelRange
    /** List of customers */
    public var items: [Customer]



}

