//
// CustomerAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomerAttributes: Codable, Sendable {

    /** List of customer attributes */
    public var items: [KeyValueEntry]?



}

