//
// CustomerData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/// - Tag: CustomerData
public struct CustomerData: Codable {

    /** Unique identifier for the customer */
    public var _id: Int64
    /** Customer name */
    public var name: String
    /** Customer is Provider Customer */
    public var isProviderCustomer: Bool
    /** Space limit (in bytes) */
    public var spaceLimit: Int64
    /** Space used (in bytes) */
    public var spaceUsed: Int64
    /** User accounts limit */
    public var accountsLimit: Int
    /** User accounts used */
    public var accountsUsed: Int
    /** Clientside encryption for customer enabled */
    public var customerEncryptionEnabled: Bool


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case isProviderCustomer
        case spaceLimit
        case spaceUsed
        case accountsLimit
        case accountsUsed
        case customerEncryptionEnabled
    }


}

