//
// DeletedNodeVersionsList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeletedNodeVersionsList: Codable, Sendable {

    /** Range */
    public var range: ModelRange
    /** List of deleted nodes */
    public var items: [DeletedNode]



}

