//
// DeletedNodeSummaryList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeletedNodeSummaryList: Codable, Sendable {

    /** Range */
    public var range: ModelRange
    /** List of deleted nodes (summary) */
    public var items: [DeletedNodeSummary]



}

