//
// DownloadShareList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/// - Tag: DownloadShareList
public struct DownloadShareList: Codable {

    /** Range */
    public var range: ModelRange
    /** List of Download Shares */
    public var items: [DownloadShare]



}

