//
// DownloadTokenGenerateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DownloadTokenGenerateResponse: Codable, Sendable {

    /** Download URL */
    public var downloadUrl: String

}

