//
// EncryptRoomRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EncryptRoomRequest: Codable, Sendable {

    /** Encryption state */
    public var isEncrypted: Bool
    /** Use system emergency password for files in this room */
    public var useDataSpaceRescueKey: Bool?
    /** Room emergency password */
    public var dataRoomRescueKey: UserKeyPairContainer?



}

