//
// FailoverServer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FailoverServer: Codable {

    /** RADIUS Failover Server is active */
    public var failoverEnabled: Bool
    /** RADIUS Failover Server IP Address Required if failover server is enabled. */
    public var failoverIpAddress: String?
    /** RADIUS Failover Server Port Required if failover server is enabled. */
    public var failoverPort: Int?



}

