//
// FileKeyContainer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FileKeyContainer: Codable, Sendable {

    /** Encryption key */
    public var key: String
    /** Initial vector */
    public var iv: String
    /** Version */
    public var version: String
    /** Authentication tag (needed with authenticated encryption) */
    public var tag: String?



}

