//
// GeneralSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GeneralSettings: Codable {

    /** Allow sending of share passwords via SMS */
    public var sharePasswordSmsEnabled: Bool?
    /** Activation status of TripleCrypt™ technology. Can only be enabled once; disabling is not possible. */
    public var cryptoEnabled: Bool?
    /** Enable email notification button */
    public var emailNotificationButtonEnabled: Bool?
    /** Each user has to confirm the EULA at first login. */
    public var eulaEnabled: Bool?
    /** Is media server enabled? */
    public var mediaServerEnabled: Bool?
    /** Allow weak password * A weak password has to fulfill the following criteria:    * is at least 8 characters long    * contains letters and numbers * A strong password has to fulfill the following criteria in addition:    * contains at least one special character    * contains upper and lower case characters */
    public var weakPasswordEnabled: Bool?
    /** Defines if S3 is used as storage backend */
    public var useS3Storage: Bool?



}

