//
// GroupUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupUser: Codable {

    /** User information */
    public var userInfo: UserInfo
    /** Determines whether user is a member of the group or not */
    public var isMember: Bool

}

