//
// Group.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Group: Codable, Sendable {

    /** Unique identifier for the group */
    public var _id: Int64
    /** Group name */
    public var name: String
    /** Creation date */
    public var createdAt: Date
    /** Created by user info */
    public var createdBy: UserInfo
    /** Amount of users */
    public var cntUsers: Int
    /** Modification date */
    public var updatedAt: Date?
    /** Modified by user info */
    public var updatedBy: UserInfo?
    /** Expiration date */
    public var expireAt: Date?
    /** Group assignment roles */
    public var groupRoles: RoleList?


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case createdAt
        case createdBy
        case cntUsers
        case updatedAt
        case updatedBy
        case expireAt
        case groupRoles
    }


}

