//
// GroupUserList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupUserList: Codable, Sendable {

    /** Range */
    public var range: ModelRange
    /** List of group-user mappings */
    public var items: [GroupUser]



}

