//
// GroupList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupList: Codable, Sendable {

    /** Range */
    public var range: ModelRange
    /** List of groups */
    public var items: [Group]



}

