//
// InfrastructureProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/// - Tag: InfrastructureProperties
public struct InfrastructureProperties: Codable {

    /** Allow sending of share passwords via SMS */
    public var smsConfigEnabled: Bool?
    /** Is media server enabled? */
    public var mediaServerConfigEnabled: Bool?
    /** Suggested S3 Region */
    public var s3DefaultRegion: String?



}

