//
// InfrastructureProperties.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/// - Tag: InfrastructureProperties
public struct InfrastructureProperties: Codable, Sendable {

    /** Allow sending of share passwords via SMS */
    public var smsConfigEnabled: Bool?
    /** Is media server enabled? */
    public var mediaServerConfigEnabled: Bool?
    /** Suggested S3 Region */
    public var s3DefaultRegion: String?
    /** Enforce direct upload to S3
     [Since version 4.13.0] */
    public var s3EnforceDirectUpload: Bool?
    /** Determines if the DRACOON Core is deployed in the cloud environment [Since v4.21.0] */
    public var isDracoonCloud: Bool?
    /** Current tenant UUID [Since v4.21.0] */
    public var tenantUuid: String?

}

