//
// KeyValueEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/// - Tag: KeyValueEntry
public struct KeyValueEntry: Codable, Sendable {
    
    public init(key: String, value: String) {
        self.key = key
        self.value = value
    }

    /** Entry key */
    public var key: String
    /** Entry value */
    public var value: String



}

