//
// LoginResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginResponse: Codable {

    /** Authentication token */
    public var token: String



}

