//
// LoginRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginRequest: Codable {

    public enum AuthType: String, Codable { 
        case sql = "sql"
        case activeDirectory = "active_directory"
        case radius = "radius"
    }
    /** User login name */
    public var login: String
    /** Password */
    public var password: String
    /** Authentication methods: * &#x60;sql&#x60; * &#x60;active_directory&#x60; * &#x60;radius&#x60; */
    public var authType: AuthType?
    /** Language ID or ISO 639-1 code */
    public var language: String?
    /** Token */
    public var token: String?
    /** For RADIUS Access-Challenge If a &#x60;replyState&#x60; is returned, it must be included as &#x60;state&#x60; in the following request. */
    public var state: String?



}

