//
// ModelErrorResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelErrorResponse: Codable, Sendable {

    /** HTTP status code */
    public var code: Int?
    /** HTTP status code description */
    public var message: String?
    /** Debug information */
    public var debugInfo: String?
    /** Error code */
    public var errorCode: Int?



}

