//
// MoveNode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MoveNode: Codable, Sendable {

    /** Source node ID */
    public var _id: Int64
    /** New node name */
    public var name: String?
    /** Time the node was created on external file system [Since version 4.22.0] */
    public var timestampCreation: String?
    /** Time the content of a node was last modified on external file system [Since version 4.22.0] */
    public var timestampModification: String?


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case timestampCreation
        case timestampModification
    }

    public init(nodeId: Int64, name: String?) {
        self._id = nodeId
        self.name = name
    }

}

