//
// NewCustomerRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NewCustomerRequest: Codable, Sendable {

    public enum CustomerContractType: String, Codable, Sendable { 
        case free = "free"
        case demo = "demo"
        case pay = "pay"
    }
    /** Customer type */
    public var customerContractType: CustomerContractType
    /** Maximal disc space which can be allocated by customer in bytes. */
    public var quotaMax: Int64
    /** Maximal number of users */
    public var userMax: Int
    /** First admin user of a customer */
    public var firstAdminUser: FirstAdminUser
    /** Company name */
    public var companyName: String?
    /** Number of days left for trial period (relevant only for type &#x60;demo&#x60;) */
    public var trialDays: Int?
    /** Determines if customer is locked */
    public var isLocked: Bool?
    /** Customer attributes */
    public var customerAttributes: CustomerAttributes?
    /** Provider customer ID value (relevant only for type &#x60;pay&#x60;) */
    public var providerCustomerId: String?
    /** Maximal number of webhooks [Since 4.19.0] */
    public var webhooksMax: Int64?


}

