//
// NodeBatchOperationErrorInfos.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodeBatchOperationErrorInfos: Codable {

    /** List of nodes that caused a conflict */
    public var conflictNodes: [ConflictNode]



}

