//
// NodeList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/// - Tag: NodeList
public struct NodeList: Codable, Sendable {

    /** Range */
    public var range: ModelRange
    /** List of nodes */
    public var items: [Node]



}

