//
// NotRestoredNodeList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NotRestoredNodeList: Codable {

    /** List of not restored nodes */
    public var items: [NotRestoredNode]



}

