//
// OpenIdAuthResources.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OpenIdAuthResources: Codable {

    /** List of available OpenID Connect identity providers */
    public var openIdProviders: [OpenIdProvider]



}

