//
// OpenIdProvider.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OpenIdProvider: Codable {

    /** ID */
    public var _id: Int
    /** Name of the IDP */
    public var name: String
    /** Issuer identifier of the IDP The value is a case sensitive URL. */
    public var issuer: String
    /** Name of the claim which is used for the user mapping. */
    public var mappingClaim: String
    /** Is available for all customers */
    public var isGlobalAvailable: Bool?


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case issuer
        case mappingClaim
        case isGlobalAvailable
    }


}

