//
// PendingAssignmentsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PendingAssignmentsRequest: Codable {

    /** List of pending assignments */
    public var items: [PendingAssignment]



}

