//
// PendingAssignment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PendingAssignment: Codable {

    public enum State: String, Codable { 
        case accepted = "ACCEPTED"
        case waiting = "WAITING"
        case denied = "DENIED"
    }
    /** Unique identifier for the user */
    public var userId: Int64
    /** Unique identifier for the group */
    public var groupId: Int64
    /** Room ID */
    public var roomId: Int64
    /** Acceptance state: * &#x60;ACCEPTED&#x60; * &#x60;WAITING&#x60; * &#x60;DENIED&#x60; */
    public var state: State



}

