//
// PrivateKeyContainer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import crypto_sdk

public struct PrivateKeyContainer: Codable {

    /** Version */
    public var version: UserKeyPairVersion
    /** Private key */
    public var privateKey: String

    public init(privateKey: String, version: UserKeyPairVersion) {
        self.privateKey = privateKey
        self.version = version
    }

}

