//
// PublicDownloadTokenGenerateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicDownloadTokenGenerateResponse: Codable {

    /** Download URL */
    public var downloadUrl: String?
    
    /** [Deprecated since v4.3.0] Download token */
    public var token: String



}

