//
// PublicUploadShare.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicUploadShare: Codable {

    /** Is share protected by password */
    public var isProtected: Bool
    /** Creation date */
    public var createdAt: Date
    /** Creator name [Since v4.11.0] */
    public var creatorName: String
    /** Creator username [Since v4.11.0] */
    public var creatorUsername: String?
    /** Share display name (alias name) */
    public var name: String?
    /** Encryption state */
    public var isEncrypted: Bool?
    /** Expiration date */
    public var expireAt: Date?
    /** User notes Use empty string to remove. */
    public var notes: String?
    /** List of (public) uploaded files */
    public var uploadedFiles: [PublicUploadedFileData]?
    /** List of user public keys */
    public var userUserPublicKeyList: UserUserPublicKeyList?
    /** Allow display of already uploaded files (default: false) */
    public var showUploadedFiles: Bool?
    /** Remaining size */
    public var remainingSize: Int64?
    /** Remaining slots */
    public var remainingSlots: Int?



}

