//
// PublicDownloadTokenGenerateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicDownloadTokenGenerateResponse: Codable {

    /** Download URL */
    public var downloadUrl: String?

}

