//
// PublicDownloadTokenGenerateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicDownloadTokenGenerateRequest: Codable, Sendable {

    /** Password (only for password-protected shares) */
    public var password: String?



}

