//
// PublicKeyContainer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicKeyContainer: Codable {

    /** Version */
    public var version: String
    /** Public key */
    public var publicKey: String

    public init(publicKey: String, version: String) {
        self.publicKey = publicKey
        self.version = version
    }


}

