//
// RadiusConfigCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RadiusConfigCreateRequest: Codable {

    /** RADIUS Server IP Address */
    public var ipAddress: String
    /** RADIUS Server Port */
    public var port: Int
    /** Shared Secret to access the RADIUS server */
    public var sharedSecret: String
    /** Sequence order of concatenated PIN and one-time token (default: true) */
    public var otpPinFirst: Bool?
    /** RADIUS Failover Server */
    public var failoverServer: FailoverServer?



}

