//
// ResetPasswordTokenValidateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResetPasswordTokenValidateResponse: Codable {

    public enum Gender: String, Codable { 
        case m = "m"
        case f = "f"
        case n = "n"
    }
    /** User first name */
    public var firstName: String
    /** User last name */
    public var lastName: String
    /** Job title */
    public var title: String?
    /** Gender */
    public var gender: Gender?
    /** Allow weak password */
    public var allowSystemGlobalWeakPassword: Bool?



}

