//
// RoleUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoleUser: Codable, Sendable {

    /** Unique identifier for the user */
    public var _id: Int64
    /** Is user member of the role */
    public var isMember: Bool
    /** Display name */
    public var displayName: String


    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case isMember
        case displayName
    }


}

