//
// RoleUserList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoleUserList: Codable, Sendable {

    /** Range */
    public var range: ModelRange
    /** List of role-user mappings */
    public var items: [RoleUser]



}

