//
// RoleGroupList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoleGroupList: Codable {

    /** Range */
    public var range: ModelRange
    /** List of role-group mappings */
    public var items: [RoleGroup]



}

