//
// RoomTreeDataList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomTreeDataList: Codable {

    /** Range */
    public var range: ModelRange
    /** List of room data information */
    public var items: [RoomData]



}

