//
// RoomGroupList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomGroupList: Codable {

    /** Range */
    public var range: ModelRange
    /** List of room-group mappings */
    public var items: [RoomGroup]



}

