//
// SoftwareVersionData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/// - Tag: SoftwareVersionData
public struct SoftwareVersionData: Codable {

    /** REST API version */
    public var restApiVersion: String
    /** DRACOON server version */
    public var sdsServerVersion: String
    /** Build date */
    public var buildDate: Date
    /** Revision number */
    public var scmRevisionNumber: String?
    /** Determines if the DRACOON Core is deployed in the cloud environment.
     [Since version 4.24.0] */
    public var isDracoonCloud: Bool?

}

