//
// UpdateGroupRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateGroupRequest: Codable, Sendable {

    /** Group name */
    public var name: String?
    /** Expiration date / time */
    public var expiration: ObjectExpiration?



}

