//
// UpdateEventlogConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateEventlogConfig: Codable {

    /** Is eventlog enabled? */
    public var enabled: Bool?
    /** Retention period (in days) of event log entries. After that period, all entries are deleted. Recommended value: 7 */
    public var retentionPeriod: Int?
    /** Determines whether user’s IP address is logged on login. */
    public var logIpEnabled: Bool?



}

