//
// UpdateRoomRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/// - Tag: UpdateRoomRequest
public struct UpdateRoomRequest: Codable {

    /** Name */
    public var name: String?
    /** Quota in byte */
    public var quota: Int64?
    /** User notes Use empty string to remove. */
    public var notes: String?

    public init() {}

}

