//
// UpdateUserAccountRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateUserAccountRequest: Codable {

    public enum Gender: String, Codable { 
        case m = "m"
        case f = "f"
        case n = "n"
    }
    /** User login name */
    public var login: String?
    /** Accept EULA Present, if EULA is system global active. cf. &#x60;GET config/settings&#x60; - &#x60;eula_active&#x60; If accepted can not be undone. */
    public var acceptEULA: Bool?
    /** Job title */
    public var title: String?
    /** User first name */
    public var firstName: String?
    /** User last name */
    public var lastName: String?
    /** Gender */
    public var gender: Gender?
    /** Email (not used) */
    public var email: String?



}

