//
// UpdateFolderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateFolderRequest: Codable {

    /** Folder name */
    public var name: String?
    /** User notes Use empty string to remove. */
    public var notes: String?

    public init() {}

}

