//
// UploadShareList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UploadShareList: Codable {

    /** Range */
    public var range: ModelRange
    /** List of Upload Shares */
    public var items: [UploadShare]



}

