//
// UserList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserList: Codable, Sendable {

    /** Range */
    public var range: ModelRange
    /** List of users */
    public var items: [UserItem]



}

