//
// UserAuthMethod.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserAuthMethod: Codable {

    /** Authentication method ID */
    public var authId: String
    /** Is enabled */
    public var isEnabled: Bool
    /** Authentication method options */
    public var options: [KeyValueEntry]?



}

