//
// UserGroupList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserGroupList: Codable, Sendable {

    /** Range */
    public var range: ModelRange
    /** List of user-group mappings */
    public var items: [UserGroup]



}

