//
// UserIds.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserIds: Codable, Sendable {

    /** List of user IDs */
    public var ids: [Int64]



}

