//
// UserIdFileIdItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserIdFileIdItem: Codable, Sendable {

    /** Unique identifier for the user */
    public var userId: Int64?
    /** File ID */
    public var fileId: Int64?



}

