//
// UserFileKeyList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserFileKeyList: Codable, Sendable {

    /** List of user file keys */
    public var items: [UserFileKey]?



}

