//
// UserInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserInfo: Codable {

    /** Unique identifier for the user */
    public var _id: Int64
    /** User type is one of
     internal, external, system or deleted
     [Since v4.11.0] */
    public var userType: String?
    /** Avatar UUID [Since v4.11.0] */
    public var avatarUuid: String?
    /** Username (only returned for internal users) [Since v4.13.0] */
    public var userName: String?
    /** User first name (mandatory if userType is internal) [Since v4.11.0] */
    public var firstName: String?
    /** User last name (mandatory if userType is internal) [Since v4.11.0] */
    public var lastName: String?
    /** Email [Since v4.11.0] */
    public var email: String?
    
    /** [Deprecated since v4.18.0] Title  */
    public var title: String?
    /** [Deprecated since v4.11.0]:  Display name */
    public var displayName: String?

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userType
        case avatarUuid
        case userName
        case firstName
        case lastName
        case email
        case title
        case displayName
    }

    public init(_id: Int64) {
        self._id = _id
    }
}

