//
// UserAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserAttributes: Codable, Sendable {

    /** List of key-value pairs */
    public var items: [KeyValueEntry]?



}

